// app/layout.jsx
import { Inter, Space_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Component/Navbar.jsx";
import Footer from "../Component/Footer.jsx";

// Load Google Fonts

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "700"], // ✅ Fix: specify available weights
});
export const metadata = {
  title: "ugaoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#317EFB" />
        <link rel="apple-touch-icon" href="/web-app-manifest-192x192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
      </head>

      <body
        className={`${inter.variable} ${spaceMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
