import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../Component/Navbar.jsx";
import Footer from "../Component/Footer.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ugaoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <head>
  <link rel="manifest" href="/manifest.json" />
  <meta name="theme-color" content="#317EFB" />
  <link rel="apple-touch-icon" href="/web-app-manifest-192x192.png" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
</head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
